# Generated by Django 5.2.17 on 2026-08-11 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_assignment_user_alter_assignment_id'),
        ('webapp', '0002_note_alter_assignment_id'),
    ]

    operations = [
    ]
